### ISSUE TITLE
Πως να το τρέξω offline?

### ISSUE THREAD

**Issue by ghost** [ioniodi/pacman#48]
Προσπαθω να τρεξω offline το pacman αλλα με τιποτα δεν τρεχει, εχω ηδη κρυψει τις 2 γραμμες που ελεγε σε σχολια μεσα στο index.html.

Προσπαθησα με chromium και firefox.

**Comment by merkourisa** [comment]
Για να τρέξεις **τοπικά** το παιχνίδι μπορείς να ακολουθήσεις τις οδηγίες από το [επίσημο site](http://phaser.io/tutorials/getting-started/index). 
Εγώ χρησιμοποιώ το [xampp](https://www.apachefriends.org/index.html) + το [eclipse](http://www.eclipse.org/) και ακολούθησα τις οδηγίες που δίνονται [εδώ](http://www.html5gamedevs.com/topic/22688-setting-up-eclipse-to-work-with-phaser-how-to/).

**Comment by ghost** [comment]
Γεια σας παλι, εχω μεγαλο προβλημα με τον χαρτη στο tiled. Προσπαθω ανοιγοντας το pacman-map.json στο tiled, και με ενα καινουργιο tileset image να κανω τις αλλαγες που θελω. Αλλα δεν ξερω ακριβως πως να το κανω να δουλεψει μεσα στο index.json αρχειο. Εχω προσπαθησει πολλες φορες και δεν βγαζω ακρη με τιποτα.

Μηπως δεν πρεπει να χρησιμοποιω πολλαπλα tilesets? Εχω το tileset "pacman-tiles.png" ΚΑΙ το tileset "basictiles"

Επισης τι ρολο παιζει το maze.json?? Δεν το βλεπω πουθενα μεσα στο index.json..

Ευχαριστω!
![screenshot_2017-10-15_13-13-53](https://user-images.githubusercontent.com/11950996/31583973-9cf9fab2-b1ad-11e7-9019-5a314ee06629.png)

**Comment by merkourisa** [comment]
Καλησπέρα,
Αρχικά άνοιξε το pacman-map.json και στη συνέχεια εντόπισε το pacman-tiles.png για να το ανοίξεις και αυτό στο tiled. Επειδή από ότι κατάλαβα δεν σου φόρτωσε κατευθείαν το pacman-tiles.png όταν φόρτωσες το pacman-map.json για αυτό έκανα μια μικρή αλλαγή στο pacman-map.json ώστε να το βλέπει κατευθείαν. Το maze.json δεν σου είναι απαραίτητο.
Τώρα για να χρησιμοποιήσεις διαφορετικό tileset θα πρέπει να το ψάξεις λίγο παραπάνω....
Στο index.html κάπου φορτώνεις τόσο το pacman-map.json όσο και το pacman-tiles.png.
