### ISSUE TITLE
Παραδοτεο 3

### ISSUE THREAD

**Issue by arachnavonfenrir** [ioniodi/pacman#57]
Το καλοκαιρι, την ημερομηνια των εξαιτασεων εκανα το κομιτ του 3ου πααραδοτεου για την εργασια αυτη ) πακμαν). Αλλα για καποια συμπτωση, το εκανα μαπον σε λαθος φακελο, και εγινε ακυρωση. Ολα καλα, θα τηο ξαναεκανα σε σψωστο φακελο, αν η ειδοποιηση για την ακυρωση του κομιτ δεν ηρθε στα σπαμ μου και το ανακαλυψα μονο προσφατα. Μηπως υπαρχει περιπτωση ενημερωσης συστηματος και βαθμολογιας?

**Comment by merkourisa** [comment]
Το issue που έχεις ανοίξει είναι σε λάθος σημείο και με όνομα που σίγουρα θα μπερδέψει άλλους φοιτητές αφού υπάρχει issue με το συγκεκριμένο όνομα. Κάνε την ερώτηση σου στο commit που έγινε reject
